/**
 * Curated demo produce listings for Greater Accra corridor.
 * Used when VITE_DEMO_MODE is on and Supabase feed is empty (screenshots / local dev).
 */
import type { FeedListing } from "@/lib/types/marketplace";

const DEMO_SELLER = "a0000001-0001-4000-8000-000000000001";

export const DEMO_FEED_LISTINGS: FeedListing[] = [
  {
    id: "demo-listing-001",
    seller_id: DEMO_SELLER,
    title: "Vine-ripe Dodowa tomatoes",
    crop_type: "tomato",
    description: "Harvested at dawn, firm and sweet.",
    price_per_unit: 12.5,
    unit: "kg",
    quantity: 120,
    hashtags: ["tomato", "organic", "dodowa"],
    location_name: "Dodowa",
    lat: 5.883,
    lng: -0.089,
    image_url: "https://images.unsplash.com/photo-1592924357228-91a4daadc663?w=800&q=80",
    video_url: "https://assets.mixkit.co/videos/preview/mixkit-close-up-of-a-fresh-red-tomato-40772-large.mp4",
    status: "active",
    view_count: 842,
    like_count: 156,
    comment_count: 23,
    save_count: 41,
    organic: true,
    created_at: new Date(Date.now() - 2 * 3_600_000).toISOString(),
    seller_name: "Ama Mensah",
    seller_slug: "ama-mensah-farm",
    seller_avatar: null,
    seller_verified: true,
    seller_rating: 4.8,
    ai_demand_score: 0.82,
    feed_score: 0.91,
    distance_km: 2.4,
  },
  {
    id: "demo-listing-002",
    seller_id: "a0000001-0001-4000-8000-000000000002",
    title: "Afienya okra — chef grade",
    crop_type: "okra",
    description: "Tender pods, zero bruising.",
    price_per_unit: 10,
    unit: "kg",
    quantity: 60,
    hashtags: ["okra", "afienya"],
    location_name: "Afienya",
    lat: 5.712,
    lng: 0.017,
    image_url: "https://images.unsplash.com/photo-1628773822503-93039bcf061c?w=800&q=80",
    video_url: null,
    status: "active",
    view_count: 412,
    like_count: 89,
    comment_count: 11,
    save_count: 22,
    organic: false,
    created_at: new Date(Date.now() - 5 * 3_600_000).toISOString(),
    seller_name: "Kofi Asante",
    seller_slug: "kofi-asante",
    seller_avatar: null,
    seller_verified: true,
    seller_rating: 4.6,
    ai_demand_score: 0.71,
    feed_score: 0.84,
    distance_km: 5.1,
  },
  {
    id: "demo-listing-003",
    seller_id: "a0000001-0001-4000-8000-000000000003",
    title: "Shito pepper blend",
    crop_type: "pepper",
    description: "Scotch bonnet + kpakpo shito ready.",
    price_per_unit: 15,
    unit: "kg",
    quantity: 45,
    hashtags: ["pepper", "shito", "accra"],
    location_name: "Tema Community 25",
    lat: 5.669,
    lng: -0.017,
    image_url: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=800&q=80",
    video_url: "https://assets.mixkit.co/videos/preview/mixkit-red-chili-peppers-close-up-41775-large.mp4",
    status: "active",
    view_count: 1204,
    like_count: 312,
    comment_count: 47,
    save_count: 88,
    organic: true,
    created_at: new Date(Date.now() - 8 * 3_600_000).toISOString(),
    seller_name: "Esi Boateng",
    seller_slug: "esi-boateng",
    seller_avatar: null,
    seller_verified: true,
    seller_rating: 4.9,
    ai_demand_score: 0.88,
    feed_score: 0.93,
    distance_km: 8.2,
  },
  {
    id: "demo-listing-004",
    seller_id: "a0000001-0001-4000-8000-000000000004",
    title: "Garden eggs — Ada Foah",
    crop_type: "garden_egg",
    description: "Small batch, white & purple mix.",
    price_per_unit: 8,
    unit: "kg",
    quantity: 90,
    hashtags: ["garden_egg", "ada"],
    location_name: "Ada Foah",
    lat: 5.786,
    lng: 0.633,
    image_url: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&q=80",
    video_url: null,
    status: "active",
    view_count: 298,
    like_count: 67,
    comment_count: 9,
    save_count: 15,
    organic: true,
    created_at: new Date(Date.now() - 12 * 3_600_000).toISOString(),
    seller_name: "Yaw Darko",
    seller_slug: "yaw-darko-farms",
    seller_avatar: null,
    seller_verified: false,
    seller_rating: 4.3,
    ai_demand_score: 0.65,
    feed_score: 0.76,
    distance_km: 12.5,
  },
  {
    id: "demo-listing-005",
    seller_id: "a0000001-0001-4000-8000-000000000005",
    title: "Morning kale & kontomire",
    crop_type: "leafy_greens",
    description: "Washed and bundled for restaurants.",
    price_per_unit: 6.5,
    unit: "bunch",
    quantity: 200,
    hashtags: ["greens", "kontomire", "accra"],
    location_name: "Osu",
    lat: 5.556,
    lng: -0.182,
    image_url: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=800&q=80",
    video_url: null,
    status: "active",
    view_count: 567,
    like_count: 134,
    comment_count: 18,
    save_count: 36,
    organic: true,
    created_at: new Date(Date.now() - 18 * 3_600_000).toISOString(),
    seller_name: "Abena Osei",
    seller_slug: "abena-osei-greens",
    seller_avatar: null,
    seller_verified: true,
    seller_rating: 4.7,
    ai_demand_score: 0.79,
    feed_score: 0.87,
    distance_km: 1.8,
  },
  {
    id: "demo-listing-006",
    seller_id: "a0000001-0001-4000-8000-000000000006",
    title: "Techiman onions — bulk",
    crop_type: "onion",
    description: "50kg sacks, corridor wholesale.",
    price_per_unit: 9,
    unit: "kg",
    quantity: 500,
    hashtags: ["onion", "wholesale"],
    location_name: "Tema Harbour",
    lat: 5.639,
    lng: -0.006,
    image_url: "https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?w=800&q=80",
    video_url: null,
    status: "active",
    view_count: 934,
    like_count: 201,
    comment_count: 31,
    save_count: 52,
    organic: false,
    created_at: new Date(Date.now() - 24 * 3_600_000).toISOString(),
    seller_name: "Kwame Adjei",
    seller_slug: "kwame-adjei-produce",
    seller_avatar: null,
    seller_verified: true,
    seller_rating: 4.5,
    ai_demand_score: 0.74,
    feed_score: 0.81,
    distance_km: 6.7,
  },
];

/** Fallback b-roll when listing has image only (react-riyils needs a video URL) */
export const FALLBACK_PRODUCE_VIDEO =
  "https://assets.mixkit.co/videos/preview/mixkit-close-up-of-a-fresh-red-tomato-40772-large.mp4";

export function isDemoMode(): boolean {
  return import.meta.env.VITE_DEMO_MODE === "true";
}

export function mergeDemoFeedIfEmpty(listings: FeedListing[]): FeedListing[] {
  if (listings.length > 0) return listings;
  if (!isDemoMode()) return listings;
  return [...DEMO_FEED_LISTINGS];
}
