/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketRouteImport } from './routes/market'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FarmersRouteImport } from './routes/farmers'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as FarmersSlugRouteImport } from './routes/farmers.$slug'
import { Route as AppTransportRouteImport } from './routes/app.transport'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppFarmerRouteImport } from './routes/app.farmer'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppBuyerRouteImport } from './routes/app.buyer'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as ApiModerateRouteImport } from './routes/api/moderate'
import { Route as ApiMapsRouteImport } from './routes/api/maps'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as AppTransportRegisterRouteImport } from './routes/app.transport.register'
import { Route as AppTransportJobsRouteImport } from './routes/app.transport.jobs'
import { Route as AppProfileViewsRouteImport } from './routes/app.profile.views'
import { Route as AppFarmerPayoutsRouteImport } from './routes/app.farmer.payouts'
import { Route as AppFarmerOrdersRouteImport } from './routes/app.farmer.orders'
import { Route as AppFarmerListingsRouteImport } from './routes/app.farmer.listings'
import { Route as AppBuyerOrdersRouteImport } from './routes/app.buyer.orders'
import { Route as AppBuyerFeedRouteImport } from './routes/app.buyer.feed'
import { Route as AppBuyerCartRouteImport } from './routes/app.buyer.cart'
import { Route as AppAdminPricingRouteImport } from './routes/app.admin.pricing'
import { Route as AppAdminPaymentsRouteImport } from './routes/app.admin.payments'
import { Route as AppAdminListingsRouteImport } from './routes/app.admin.listings'
import { Route as AppAdminDisputesRouteImport } from './routes/app.admin.disputes'
import { Route as ApiWebhooksPaystackRouteImport } from './routes/api/webhooks/paystack'
import { Route as ApiVerifyGhanaCardRouteImport } from './routes/api/verify/ghana-card'
import { Route as ApiSettingsNotificationsRouteImport } from './routes/api/settings/notifications'
import { Route as ApiSearchGlobalRouteImport } from './routes/api/search/global'
import { Route as ApiPushRegisterRouteImport } from './routes/api/push/register'
import { Route as ApiProfileViewRouteImport } from './routes/api/profile/view'
import { Route as ApiOtpVerifyRouteImport } from './routes/api/otp/verify'
import { Route as ApiOtpSendRouteImport } from './routes/api/otp/send'
import { Route as ApiDeliveryQuoteRouteImport } from './routes/api/delivery/quote'
import { Route as ApiDeliveriesReassignExpiredRouteImport } from './routes/api/deliveries/reassign-expired'
import { Route as ApiDeliveriesDeclineRouteImport } from './routes/api/deliveries/decline'
import { Route as ApiDeliveriesCompleteRouteImport } from './routes/api/deliveries/complete'
import { Route as ApiDeliveriesAcceptRouteImport } from './routes/api/deliveries/accept'
import { Route as ApiCommsNotifyRouteImport } from './routes/api/comms/notify'
import { Route as ApiChatSendRouteImport } from './routes/api/chat/send'
import { Route as ApiChatRequestRouteImport } from './routes/api/chat/request'
import { Route as ApiAdminPricingRouteImport } from './routes/api/admin/pricing'
import { Route as AppInboxChatUserIdRouteImport } from './routes/app.inbox.chat.$userId'
import { Route as AppBuyerOrdersOrderIdTrackRouteImport } from './routes/app.buyer.orders.$orderId.track'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersRoute = FarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const FarmersSlugRoute = FarmersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FarmersRoute,
} as any)
const AppTransportRoute = AppTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmerRoute = AppFarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerRoute = AppBuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiModerateRoute = ApiModerateRouteImport.update({
  id: '/api/moderate',
  path: '/api/moderate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapsRoute = ApiMapsRouteImport.update({
  id: '/api/maps',
  path: '/api/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransportRegisterRoute = AppTransportRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppTransportRoute,
} as any)
const AppTransportJobsRoute = AppTransportJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppTransportRoute,
} as any)
const AppProfileViewsRoute = AppProfileViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppFarmerPayoutsRoute = AppFarmerPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppFarmerRoute,
} as any)
const AppFarmerOrdersRoute = AppFarmerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppFarmerRoute,
} as any)
const AppFarmerListingsRoute = AppFarmerListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AppFarmerRoute,
} as any)
const AppBuyerOrdersRoute = AppBuyerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppBuyerRoute,
} as any)
const AppBuyerFeedRoute = AppBuyerFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppBuyerRoute,
} as any)
const AppBuyerCartRoute = AppBuyerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppBuyerRoute,
} as any)
const AppAdminPricingRoute = AppAdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPaymentsRoute = AppAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminListingsRoute = AppAdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDisputesRoute = AppAdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiWebhooksPaystackRoute = ApiWebhooksPaystackRouteImport.update({
  id: '/api/webhooks/paystack',
  path: '/api/webhooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyGhanaCardRoute = ApiVerifyGhanaCardRouteImport.update({
  id: '/api/verify/ghana-card',
  path: '/api/verify/ghana-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsNotificationsRoute =
  ApiSettingsNotificationsRouteImport.update({
    id: '/api/settings/notifications',
    path: '/api/settings/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSearchGlobalRoute = ApiSearchGlobalRouteImport.update({
  id: '/api/search/global',
  path: '/api/search/global',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRegisterRoute = ApiPushRegisterRouteImport.update({
  id: '/api/push/register',
  path: '/api/push/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileViewRoute = ApiProfileViewRouteImport.update({
  id: '/api/profile/view',
  path: '/api/profile/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOtpVerifyRoute = ApiOtpVerifyRouteImport.update({
  id: '/api/otp/verify',
  path: '/api/otp/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOtpSendRoute = ApiOtpSendRouteImport.update({
  id: '/api/otp/send',
  path: '/api/otp/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliveryQuoteRoute = ApiDeliveryQuoteRouteImport.update({
  id: '/api/delivery/quote',
  path: '/api/delivery/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliveriesReassignExpiredRoute =
  ApiDeliveriesReassignExpiredRouteImport.update({
    id: '/api/deliveries/reassign-expired',
    path: '/api/deliveries/reassign-expired',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDeliveriesDeclineRoute = ApiDeliveriesDeclineRouteImport.update({
  id: '/api/deliveries/decline',
  path: '/api/deliveries/decline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliveriesCompleteRoute = ApiDeliveriesCompleteRouteImport.update({
  id: '/api/deliveries/complete',
  path: '/api/deliveries/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliveriesAcceptRoute = ApiDeliveriesAcceptRouteImport.update({
  id: '/api/deliveries/accept',
  path: '/api/deliveries/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommsNotifyRoute = ApiCommsNotifyRouteImport.update({
  id: '/api/comms/notify',
  path: '/api/comms/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSendRoute = ApiChatSendRouteImport.update({
  id: '/api/chat/send',
  path: '/api/chat/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRequestRoute = ApiChatRequestRouteImport.update({
  id: '/api/chat/request',
  path: '/api/chat/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPricingRoute = ApiAdminPricingRouteImport.update({
  id: '/api/admin/pricing',
  path: '/api/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxChatUserIdRoute = AppInboxChatUserIdRouteImport.update({
  id: '/chat/$userId',
  path: '/chat/$userId',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppBuyerOrdersOrderIdTrackRoute =
  AppBuyerOrdersOrderIdTrackRouteImport.update({
    id: '/$orderId/track',
    path: '/$orderId/track',
    getParentRoute: () => AppBuyerOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/farmers': typeof FarmersRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/market': typeof MarketRoute
  '/pricing': typeof PricingRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/maps': typeof ApiMapsRoute
  '/api/moderate': typeof ApiModerateRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/buyer': typeof AppBuyerRouteWithChildren
  '/app/create': typeof AppCreateRoute
  '/app/farmer': typeof AppFarmerRouteWithChildren
  '/app/inbox': typeof AppInboxRouteWithChildren
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/transport': typeof AppTransportRouteWithChildren
  '/farmers/$slug': typeof FarmersSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/admin/pricing': typeof ApiAdminPricingRoute
  '/api/chat/request': typeof ApiChatRequestRoute
  '/api/chat/send': typeof ApiChatSendRoute
  '/api/comms/notify': typeof ApiCommsNotifyRoute
  '/api/deliveries/accept': typeof ApiDeliveriesAcceptRoute
  '/api/deliveries/complete': typeof ApiDeliveriesCompleteRoute
  '/api/deliveries/decline': typeof ApiDeliveriesDeclineRoute
  '/api/deliveries/reassign-expired': typeof ApiDeliveriesReassignExpiredRoute
  '/api/delivery/quote': typeof ApiDeliveryQuoteRoute
  '/api/otp/send': typeof ApiOtpSendRoute
  '/api/otp/verify': typeof ApiOtpVerifyRoute
  '/api/profile/view': typeof ApiProfileViewRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/search/global': typeof ApiSearchGlobalRoute
  '/api/settings/notifications': typeof ApiSettingsNotificationsRoute
  '/api/verify/ghana-card': typeof ApiVerifyGhanaCardRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/app/admin/disputes': typeof AppAdminDisputesRoute
  '/app/admin/listings': typeof AppAdminListingsRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/pricing': typeof AppAdminPricingRoute
  '/app/buyer/cart': typeof AppBuyerCartRoute
  '/app/buyer/feed': typeof AppBuyerFeedRoute
  '/app/buyer/orders': typeof AppBuyerOrdersRouteWithChildren
  '/app/farmer/listings': typeof AppFarmerListingsRoute
  '/app/farmer/orders': typeof AppFarmerOrdersRoute
  '/app/farmer/payouts': typeof AppFarmerPayoutsRoute
  '/app/profile/views': typeof AppProfileViewsRoute
  '/app/transport/jobs': typeof AppTransportJobsRoute
  '/app/transport/register': typeof AppTransportRegisterRoute
  '/app/inbox/chat/$userId': typeof AppInboxChatUserIdRoute
  '/app/buyer/orders/$orderId/track': typeof AppBuyerOrdersOrderIdTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/farmers': typeof FarmersRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/market': typeof MarketRoute
  '/pricing': typeof PricingRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/maps': typeof ApiMapsRoute
  '/api/moderate': typeof ApiModerateRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/buyer': typeof AppBuyerRouteWithChildren
  '/app/create': typeof AppCreateRoute
  '/app/farmer': typeof AppFarmerRouteWithChildren
  '/app/inbox': typeof AppInboxRouteWithChildren
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/transport': typeof AppTransportRouteWithChildren
  '/farmers/$slug': typeof FarmersSlugRoute
  '/app': typeof AppIndexRoute
  '/api/admin/pricing': typeof ApiAdminPricingRoute
  '/api/chat/request': typeof ApiChatRequestRoute
  '/api/chat/send': typeof ApiChatSendRoute
  '/api/comms/notify': typeof ApiCommsNotifyRoute
  '/api/deliveries/accept': typeof ApiDeliveriesAcceptRoute
  '/api/deliveries/complete': typeof ApiDeliveriesCompleteRoute
  '/api/deliveries/decline': typeof ApiDeliveriesDeclineRoute
  '/api/deliveries/reassign-expired': typeof ApiDeliveriesReassignExpiredRoute
  '/api/delivery/quote': typeof ApiDeliveryQuoteRoute
  '/api/otp/send': typeof ApiOtpSendRoute
  '/api/otp/verify': typeof ApiOtpVerifyRoute
  '/api/profile/view': typeof ApiProfileViewRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/search/global': typeof ApiSearchGlobalRoute
  '/api/settings/notifications': typeof ApiSettingsNotificationsRoute
  '/api/verify/ghana-card': typeof ApiVerifyGhanaCardRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/app/admin/disputes': typeof AppAdminDisputesRoute
  '/app/admin/listings': typeof AppAdminListingsRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/pricing': typeof AppAdminPricingRoute
  '/app/buyer/cart': typeof AppBuyerCartRoute
  '/app/buyer/feed': typeof AppBuyerFeedRoute
  '/app/buyer/orders': typeof AppBuyerOrdersRouteWithChildren
  '/app/farmer/listings': typeof AppFarmerListingsRoute
  '/app/farmer/orders': typeof AppFarmerOrdersRoute
  '/app/farmer/payouts': typeof AppFarmerPayoutsRoute
  '/app/profile/views': typeof AppProfileViewsRoute
  '/app/transport/jobs': typeof AppTransportJobsRoute
  '/app/transport/register': typeof AppTransportRegisterRoute
  '/app/inbox/chat/$userId': typeof AppInboxChatUserIdRoute
  '/app/buyer/orders/$orderId/track': typeof AppBuyerOrdersOrderIdTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/farmers': typeof FarmersRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/market': typeof MarketRoute
  '/pricing': typeof PricingRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/maps': typeof ApiMapsRoute
  '/api/moderate': typeof ApiModerateRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/buyer': typeof AppBuyerRouteWithChildren
  '/app/create': typeof AppCreateRoute
  '/app/farmer': typeof AppFarmerRouteWithChildren
  '/app/inbox': typeof AppInboxRouteWithChildren
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/transport': typeof AppTransportRouteWithChildren
  '/farmers/$slug': typeof FarmersSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/admin/pricing': typeof ApiAdminPricingRoute
  '/api/chat/request': typeof ApiChatRequestRoute
  '/api/chat/send': typeof ApiChatSendRoute
  '/api/comms/notify': typeof ApiCommsNotifyRoute
  '/api/deliveries/accept': typeof ApiDeliveriesAcceptRoute
  '/api/deliveries/complete': typeof ApiDeliveriesCompleteRoute
  '/api/deliveries/decline': typeof ApiDeliveriesDeclineRoute
  '/api/deliveries/reassign-expired': typeof ApiDeliveriesReassignExpiredRoute
  '/api/delivery/quote': typeof ApiDeliveryQuoteRoute
  '/api/otp/send': typeof ApiOtpSendRoute
  '/api/otp/verify': typeof ApiOtpVerifyRoute
  '/api/profile/view': typeof ApiProfileViewRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/search/global': typeof ApiSearchGlobalRoute
  '/api/settings/notifications': typeof ApiSettingsNotificationsRoute
  '/api/verify/ghana-card': typeof ApiVerifyGhanaCardRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/app/admin/disputes': typeof AppAdminDisputesRoute
  '/app/admin/listings': typeof AppAdminListingsRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/pricing': typeof AppAdminPricingRoute
  '/app/buyer/cart': typeof AppBuyerCartRoute
  '/app/buyer/feed': typeof AppBuyerFeedRoute
  '/app/buyer/orders': typeof AppBuyerOrdersRouteWithChildren
  '/app/farmer/listings': typeof AppFarmerListingsRoute
  '/app/farmer/orders': typeof AppFarmerOrdersRoute
  '/app/farmer/payouts': typeof AppFarmerPayoutsRoute
  '/app/profile/views': typeof AppProfileViewsRoute
  '/app/transport/jobs': typeof AppTransportJobsRoute
  '/app/transport/register': typeof AppTransportRegisterRoute
  '/app/inbox/chat/$userId': typeof AppInboxChatUserIdRoute
  '/app/buyer/orders/$orderId/track': typeof AppBuyerOrdersOrderIdTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/discover'
    | '/farmers'
    | '/how-it-works'
    | '/market'
    | '/pricing'
    | '/api/checkout'
    | '/api/maps'
    | '/api/moderate'
    | '/app/admin'
    | '/app/buyer'
    | '/app/create'
    | '/app/farmer'
    | '/app/inbox'
    | '/app/profile'
    | '/app/settings'
    | '/app/transport'
    | '/farmers/$slug'
    | '/app/'
    | '/api/admin/pricing'
    | '/api/chat/request'
    | '/api/chat/send'
    | '/api/comms/notify'
    | '/api/deliveries/accept'
    | '/api/deliveries/complete'
    | '/api/deliveries/decline'
    | '/api/deliveries/reassign-expired'
    | '/api/delivery/quote'
    | '/api/otp/send'
    | '/api/otp/verify'
    | '/api/profile/view'
    | '/api/push/register'
    | '/api/search/global'
    | '/api/settings/notifications'
    | '/api/verify/ghana-card'
    | '/api/webhooks/paystack'
    | '/app/admin/disputes'
    | '/app/admin/listings'
    | '/app/admin/payments'
    | '/app/admin/pricing'
    | '/app/buyer/cart'
    | '/app/buyer/feed'
    | '/app/buyer/orders'
    | '/app/farmer/listings'
    | '/app/farmer/orders'
    | '/app/farmer/payouts'
    | '/app/profile/views'
    | '/app/transport/jobs'
    | '/app/transport/register'
    | '/app/inbox/chat/$userId'
    | '/app/buyer/orders/$orderId/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/discover'
    | '/farmers'
    | '/how-it-works'
    | '/market'
    | '/pricing'
    | '/api/checkout'
    | '/api/maps'
    | '/api/moderate'
    | '/app/admin'
    | '/app/buyer'
    | '/app/create'
    | '/app/farmer'
    | '/app/inbox'
    | '/app/profile'
    | '/app/settings'
    | '/app/transport'
    | '/farmers/$slug'
    | '/app'
    | '/api/admin/pricing'
    | '/api/chat/request'
    | '/api/chat/send'
    | '/api/comms/notify'
    | '/api/deliveries/accept'
    | '/api/deliveries/complete'
    | '/api/deliveries/decline'
    | '/api/deliveries/reassign-expired'
    | '/api/delivery/quote'
    | '/api/otp/send'
    | '/api/otp/verify'
    | '/api/profile/view'
    | '/api/push/register'
    | '/api/search/global'
    | '/api/settings/notifications'
    | '/api/verify/ghana-card'
    | '/api/webhooks/paystack'
    | '/app/admin/disputes'
    | '/app/admin/listings'
    | '/app/admin/payments'
    | '/app/admin/pricing'
    | '/app/buyer/cart'
    | '/app/buyer/feed'
    | '/app/buyer/orders'
    | '/app/farmer/listings'
    | '/app/farmer/orders'
    | '/app/farmer/payouts'
    | '/app/profile/views'
    | '/app/transport/jobs'
    | '/app/transport/register'
    | '/app/inbox/chat/$userId'
    | '/app/buyer/orders/$orderId/track'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/discover'
    | '/farmers'
    | '/how-it-works'
    | '/market'
    | '/pricing'
    | '/api/checkout'
    | '/api/maps'
    | '/api/moderate'
    | '/app/admin'
    | '/app/buyer'
    | '/app/create'
    | '/app/farmer'
    | '/app/inbox'
    | '/app/profile'
    | '/app/settings'
    | '/app/transport'
    | '/farmers/$slug'
    | '/app/'
    | '/api/admin/pricing'
    | '/api/chat/request'
    | '/api/chat/send'
    | '/api/comms/notify'
    | '/api/deliveries/accept'
    | '/api/deliveries/complete'
    | '/api/deliveries/decline'
    | '/api/deliveries/reassign-expired'
    | '/api/delivery/quote'
    | '/api/otp/send'
    | '/api/otp/verify'
    | '/api/profile/view'
    | '/api/push/register'
    | '/api/search/global'
    | '/api/settings/notifications'
    | '/api/verify/ghana-card'
    | '/api/webhooks/paystack'
    | '/app/admin/disputes'
    | '/app/admin/listings'
    | '/app/admin/payments'
    | '/app/admin/pricing'
    | '/app/buyer/cart'
    | '/app/buyer/feed'
    | '/app/buyer/orders'
    | '/app/farmer/listings'
    | '/app/farmer/orders'
    | '/app/farmer/payouts'
    | '/app/profile/views'
    | '/app/transport/jobs'
    | '/app/transport/register'
    | '/app/inbox/chat/$userId'
    | '/app/buyer/orders/$orderId/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DiscoverRoute: typeof DiscoverRoute
  FarmersRoute: typeof FarmersRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  MarketRoute: typeof MarketRoute
  PricingRoute: typeof PricingRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiMapsRoute: typeof ApiMapsRoute
  ApiModerateRoute: typeof ApiModerateRoute
  ApiAdminPricingRoute: typeof ApiAdminPricingRoute
  ApiChatRequestRoute: typeof ApiChatRequestRoute
  ApiChatSendRoute: typeof ApiChatSendRoute
  ApiCommsNotifyRoute: typeof ApiCommsNotifyRoute
  ApiDeliveriesAcceptRoute: typeof ApiDeliveriesAcceptRoute
  ApiDeliveriesCompleteRoute: typeof ApiDeliveriesCompleteRoute
  ApiDeliveriesDeclineRoute: typeof ApiDeliveriesDeclineRoute
  ApiDeliveriesReassignExpiredRoute: typeof ApiDeliveriesReassignExpiredRoute
  ApiDeliveryQuoteRoute: typeof ApiDeliveryQuoteRoute
  ApiOtpSendRoute: typeof ApiOtpSendRoute
  ApiOtpVerifyRoute: typeof ApiOtpVerifyRoute
  ApiProfileViewRoute: typeof ApiProfileViewRoute
  ApiPushRegisterRoute: typeof ApiPushRegisterRoute
  ApiSearchGlobalRoute: typeof ApiSearchGlobalRoute
  ApiSettingsNotificationsRoute: typeof ApiSettingsNotificationsRoute
  ApiVerifyGhanaCardRoute: typeof ApiVerifyGhanaCardRoute
  ApiWebhooksPaystackRoute: typeof ApiWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers': {
      id: '/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof FarmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/farmers/$slug': {
      id: '/farmers/$slug'
      path: '/$slug'
      fullPath: '/farmers/$slug'
      preLoaderRoute: typeof FarmersSlugRouteImport
      parentRoute: typeof FarmersRoute
    }
    '/app/transport': {
      id: '/app/transport'
      path: '/transport'
      fullPath: '/app/transport'
      preLoaderRoute: typeof AppTransportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/farmer': {
      id: '/app/farmer'
      path: '/farmer'
      fullPath: '/app/farmer'
      preLoaderRoute: typeof AppFarmerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyer': {
      id: '/app/buyer'
      path: '/buyer'
      fullPath: '/app/buyer'
      preLoaderRoute: typeof AppBuyerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/moderate': {
      id: '/api/moderate'
      path: '/api/moderate'
      fullPath: '/api/moderate'
      preLoaderRoute: typeof ApiModerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maps': {
      id: '/api/maps'
      path: '/api/maps'
      fullPath: '/api/maps'
      preLoaderRoute: typeof ApiMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transport/register': {
      id: '/app/transport/register'
      path: '/register'
      fullPath: '/app/transport/register'
      preLoaderRoute: typeof AppTransportRegisterRouteImport
      parentRoute: typeof AppTransportRoute
    }
    '/app/transport/jobs': {
      id: '/app/transport/jobs'
      path: '/jobs'
      fullPath: '/app/transport/jobs'
      preLoaderRoute: typeof AppTransportJobsRouteImport
      parentRoute: typeof AppTransportRoute
    }
    '/app/profile/views': {
      id: '/app/profile/views'
      path: '/views'
      fullPath: '/app/profile/views'
      preLoaderRoute: typeof AppProfileViewsRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/app/farmer/payouts': {
      id: '/app/farmer/payouts'
      path: '/payouts'
      fullPath: '/app/farmer/payouts'
      preLoaderRoute: typeof AppFarmerPayoutsRouteImport
      parentRoute: typeof AppFarmerRoute
    }
    '/app/farmer/orders': {
      id: '/app/farmer/orders'
      path: '/orders'
      fullPath: '/app/farmer/orders'
      preLoaderRoute: typeof AppFarmerOrdersRouteImport
      parentRoute: typeof AppFarmerRoute
    }
    '/app/farmer/listings': {
      id: '/app/farmer/listings'
      path: '/listings'
      fullPath: '/app/farmer/listings'
      preLoaderRoute: typeof AppFarmerListingsRouteImport
      parentRoute: typeof AppFarmerRoute
    }
    '/app/buyer/orders': {
      id: '/app/buyer/orders'
      path: '/orders'
      fullPath: '/app/buyer/orders'
      preLoaderRoute: typeof AppBuyerOrdersRouteImport
      parentRoute: typeof AppBuyerRoute
    }
    '/app/buyer/feed': {
      id: '/app/buyer/feed'
      path: '/feed'
      fullPath: '/app/buyer/feed'
      preLoaderRoute: typeof AppBuyerFeedRouteImport
      parentRoute: typeof AppBuyerRoute
    }
    '/app/buyer/cart': {
      id: '/app/buyer/cart'
      path: '/cart'
      fullPath: '/app/buyer/cart'
      preLoaderRoute: typeof AppBuyerCartRouteImport
      parentRoute: typeof AppBuyerRoute
    }
    '/app/admin/pricing': {
      id: '/app/admin/pricing'
      path: '/pricing'
      fullPath: '/app/admin/pricing'
      preLoaderRoute: typeof AppAdminPricingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/payments': {
      id: '/app/admin/payments'
      path: '/payments'
      fullPath: '/app/admin/payments'
      preLoaderRoute: typeof AppAdminPaymentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/listings': {
      id: '/app/admin/listings'
      path: '/listings'
      fullPath: '/app/admin/listings'
      preLoaderRoute: typeof AppAdminListingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/disputes': {
      id: '/app/admin/disputes'
      path: '/disputes'
      fullPath: '/app/admin/disputes'
      preLoaderRoute: typeof AppAdminDisputesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/webhooks/paystack': {
      id: '/api/webhooks/paystack'
      path: '/api/webhooks/paystack'
      fullPath: '/api/webhooks/paystack'
      preLoaderRoute: typeof ApiWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify/ghana-card': {
      id: '/api/verify/ghana-card'
      path: '/api/verify/ghana-card'
      fullPath: '/api/verify/ghana-card'
      preLoaderRoute: typeof ApiVerifyGhanaCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/notifications': {
      id: '/api/settings/notifications'
      path: '/api/settings/notifications'
      fullPath: '/api/settings/notifications'
      preLoaderRoute: typeof ApiSettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/global': {
      id: '/api/search/global'
      path: '/api/search/global'
      fullPath: '/api/search/global'
      preLoaderRoute: typeof ApiSearchGlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/register': {
      id: '/api/push/register'
      path: '/api/push/register'
      fullPath: '/api/push/register'
      preLoaderRoute: typeof ApiPushRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/view': {
      id: '/api/profile/view'
      path: '/api/profile/view'
      fullPath: '/api/profile/view'
      preLoaderRoute: typeof ApiProfileViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/otp/verify': {
      id: '/api/otp/verify'
      path: '/api/otp/verify'
      fullPath: '/api/otp/verify'
      preLoaderRoute: typeof ApiOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/otp/send': {
      id: '/api/otp/send'
      path: '/api/otp/send'
      fullPath: '/api/otp/send'
      preLoaderRoute: typeof ApiOtpSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delivery/quote': {
      id: '/api/delivery/quote'
      path: '/api/delivery/quote'
      fullPath: '/api/delivery/quote'
      preLoaderRoute: typeof ApiDeliveryQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deliveries/reassign-expired': {
      id: '/api/deliveries/reassign-expired'
      path: '/api/deliveries/reassign-expired'
      fullPath: '/api/deliveries/reassign-expired'
      preLoaderRoute: typeof ApiDeliveriesReassignExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deliveries/decline': {
      id: '/api/deliveries/decline'
      path: '/api/deliveries/decline'
      fullPath: '/api/deliveries/decline'
      preLoaderRoute: typeof ApiDeliveriesDeclineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deliveries/complete': {
      id: '/api/deliveries/complete'
      path: '/api/deliveries/complete'
      fullPath: '/api/deliveries/complete'
      preLoaderRoute: typeof ApiDeliveriesCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deliveries/accept': {
      id: '/api/deliveries/accept'
      path: '/api/deliveries/accept'
      fullPath: '/api/deliveries/accept'
      preLoaderRoute: typeof ApiDeliveriesAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comms/notify': {
      id: '/api/comms/notify'
      path: '/api/comms/notify'
      fullPath: '/api/comms/notify'
      preLoaderRoute: typeof ApiCommsNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/send': {
      id: '/api/chat/send'
      path: '/api/chat/send'
      fullPath: '/api/chat/send'
      preLoaderRoute: typeof ApiChatSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/request': {
      id: '/api/chat/request'
      path: '/api/chat/request'
      fullPath: '/api/chat/request'
      preLoaderRoute: typeof ApiChatRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pricing': {
      id: '/api/admin/pricing'
      path: '/api/admin/pricing'
      fullPath: '/api/admin/pricing'
      preLoaderRoute: typeof ApiAdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inbox/chat/$userId': {
      id: '/app/inbox/chat/$userId'
      path: '/chat/$userId'
      fullPath: '/app/inbox/chat/$userId'
      preLoaderRoute: typeof AppInboxChatUserIdRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/app/buyer/orders/$orderId/track': {
      id: '/app/buyer/orders/$orderId/track'
      path: '/$orderId/track'
      fullPath: '/app/buyer/orders/$orderId/track'
      preLoaderRoute: typeof AppBuyerOrdersOrderIdTrackRouteImport
      parentRoute: typeof AppBuyerOrdersRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminDisputesRoute: typeof AppAdminDisputesRoute
  AppAdminListingsRoute: typeof AppAdminListingsRoute
  AppAdminPaymentsRoute: typeof AppAdminPaymentsRoute
  AppAdminPricingRoute: typeof AppAdminPricingRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminDisputesRoute: AppAdminDisputesRoute,
  AppAdminListingsRoute: AppAdminListingsRoute,
  AppAdminPaymentsRoute: AppAdminPaymentsRoute,
  AppAdminPricingRoute: AppAdminPricingRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppBuyerOrdersRouteChildren {
  AppBuyerOrdersOrderIdTrackRoute: typeof AppBuyerOrdersOrderIdTrackRoute
}

const AppBuyerOrdersRouteChildren: AppBuyerOrdersRouteChildren = {
  AppBuyerOrdersOrderIdTrackRoute: AppBuyerOrdersOrderIdTrackRoute,
}

const AppBuyerOrdersRouteWithChildren = AppBuyerOrdersRoute._addFileChildren(
  AppBuyerOrdersRouteChildren,
)

interface AppBuyerRouteChildren {
  AppBuyerCartRoute: typeof AppBuyerCartRoute
  AppBuyerFeedRoute: typeof AppBuyerFeedRoute
  AppBuyerOrdersRoute: typeof AppBuyerOrdersRouteWithChildren
}

const AppBuyerRouteChildren: AppBuyerRouteChildren = {
  AppBuyerCartRoute: AppBuyerCartRoute,
  AppBuyerFeedRoute: AppBuyerFeedRoute,
  AppBuyerOrdersRoute: AppBuyerOrdersRouteWithChildren,
}

const AppBuyerRouteWithChildren = AppBuyerRoute._addFileChildren(
  AppBuyerRouteChildren,
)

interface AppFarmerRouteChildren {
  AppFarmerListingsRoute: typeof AppFarmerListingsRoute
  AppFarmerOrdersRoute: typeof AppFarmerOrdersRoute
  AppFarmerPayoutsRoute: typeof AppFarmerPayoutsRoute
}

const AppFarmerRouteChildren: AppFarmerRouteChildren = {
  AppFarmerListingsRoute: AppFarmerListingsRoute,
  AppFarmerOrdersRoute: AppFarmerOrdersRoute,
  AppFarmerPayoutsRoute: AppFarmerPayoutsRoute,
}

const AppFarmerRouteWithChildren = AppFarmerRoute._addFileChildren(
  AppFarmerRouteChildren,
)

interface AppInboxRouteChildren {
  AppInboxChatUserIdRoute: typeof AppInboxChatUserIdRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxChatUserIdRoute: AppInboxChatUserIdRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

interface AppProfileRouteChildren {
  AppProfileViewsRoute: typeof AppProfileViewsRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileViewsRoute: AppProfileViewsRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppTransportRouteChildren {
  AppTransportJobsRoute: typeof AppTransportJobsRoute
  AppTransportRegisterRoute: typeof AppTransportRegisterRoute
}

const AppTransportRouteChildren: AppTransportRouteChildren = {
  AppTransportJobsRoute: AppTransportJobsRoute,
  AppTransportRegisterRoute: AppTransportRegisterRoute,
}

const AppTransportRouteWithChildren = AppTransportRoute._addFileChildren(
  AppTransportRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBuyerRoute: typeof AppBuyerRouteWithChildren
  AppCreateRoute: typeof AppCreateRoute
  AppFarmerRoute: typeof AppFarmerRouteWithChildren
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransportRoute: typeof AppTransportRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBuyerRoute: AppBuyerRouteWithChildren,
  AppCreateRoute: AppCreateRoute,
  AppFarmerRoute: AppFarmerRouteWithChildren,
  AppInboxRoute: AppInboxRouteWithChildren,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTransportRoute: AppTransportRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface FarmersRouteChildren {
  FarmersSlugRoute: typeof FarmersSlugRoute
}

const FarmersRouteChildren: FarmersRouteChildren = {
  FarmersSlugRoute: FarmersSlugRoute,
}

const FarmersRouteWithChildren =
  FarmersRoute._addFileChildren(FarmersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DiscoverRoute: DiscoverRoute,
  FarmersRoute: FarmersRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  MarketRoute: MarketRoute,
  PricingRoute: PricingRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiMapsRoute: ApiMapsRoute,
  ApiModerateRoute: ApiModerateRoute,
  ApiAdminPricingRoute: ApiAdminPricingRoute,
  ApiChatRequestRoute: ApiChatRequestRoute,
  ApiChatSendRoute: ApiChatSendRoute,
  ApiCommsNotifyRoute: ApiCommsNotifyRoute,
  ApiDeliveriesAcceptRoute: ApiDeliveriesAcceptRoute,
  ApiDeliveriesCompleteRoute: ApiDeliveriesCompleteRoute,
  ApiDeliveriesDeclineRoute: ApiDeliveriesDeclineRoute,
  ApiDeliveriesReassignExpiredRoute: ApiDeliveriesReassignExpiredRoute,
  ApiDeliveryQuoteRoute: ApiDeliveryQuoteRoute,
  ApiOtpSendRoute: ApiOtpSendRoute,
  ApiOtpVerifyRoute: ApiOtpVerifyRoute,
  ApiProfileViewRoute: ApiProfileViewRoute,
  ApiPushRegisterRoute: ApiPushRegisterRoute,
  ApiSearchGlobalRoute: ApiSearchGlobalRoute,
  ApiSettingsNotificationsRoute: ApiSettingsNotificationsRoute,
  ApiVerifyGhanaCardRoute: ApiVerifyGhanaCardRoute,
  ApiWebhooksPaystackRoute: ApiWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
